### ISSUE TITLE
ReferenceError: HTMLElement is not defined in Next.js 13

### ISSUE THREAD

**Issue by sajjad5221** [javadbat/jb-date-input-react#1]
Hi
When running `npm run build` in a Next.js 13 application, I am seeing the following error:
ReferenceError: HTMLElement is not defined

**Comment by javadbat** [comment]
because jb-date-input-react using web-component internally you can't server-side render it  and you should load it in dynamic mode:
```javascript
const JBDateInput = dynamic(() => import('jb-date-input-react').then(module => module.JBDateInput), {
  ssr: false,
});
```
to see sample code using nextjs read this file:
[sample](https://github.com/javadbat/jb-date-input-react/blob/main/docs/src/components/samples/Samples.tsx)

**Comment by javadbat** [comment]
@sajjad5221

**Comment by sajjad5221** [comment]
> because jb-date-input-react using web-component internally you can't server-side render it and you should load it in dynamic mode:
> 
> ```js
> const JBDateInput = dynamic(() => import('jb-date-input-react').then(module => module.JBDateInput), {
>   ssr: false,
> });
> ```
> 
> to see sample code using nextjs read this file: [sample](https://github.com/javadbat/jb-date-input-react/blob/main/docs/src/components/samples/Samples.tsx)

It worked! Thank you.
